# Generated by Django 2.2.16 on 2020-09-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_magazine_airline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssueView',
            new_name='IssueProgress',
        ),
    ]
