# Generated by Django 2.2.16 on 2020-09-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200902_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='icon',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='cover_image_link',
            field=models.CharField(max_length=200),
        ),
    ]
